name: test version

on:
  repository_dispatch:
    types:
      - pact-ffi-released
  workflow_dispatch:
    inputs:
        PACT_FFI_VERSION:
            description: Tag from https://github.com/you54f/pact-reference/releases for libpact_ffi
            required: true
            default: 0.4.18
            type: string

jobs:
  release:
    name: Release update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Config github actor
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git config pull.ff only

      - name: Create PR with updated ffi version
        run: |
            echo "âš—ï¸  Sorting out the ffi version... "
            git checkout -b version/v${{ inputs.PACT_FFI_VERSION }}
            rm -rf FFI_VERSION
            echo '${{ inputs.PACT_FFI_VERSION }}' >> FFI_VERSION
            git add FFI_VERSION
            git commit -m "chore(version): update version to v${{ inputs.PACT_FFI_VERSION }}"
            git push --set-upstream origin version/v${{ inputs.PACT_FFI_VERSION }}
        
            echo "ğŸ‘  Go and open that PR now:"
            echo "ğŸ”—  ${{ env.HOMEPAGE }}/compare/main...version/v${{ inputs.PACT_FFI_VERSION }}"
        
            gh pr create --title "ci(test): Update version to v${{ inputs.PACT_FFI_VERSION }}" --fill
        
            echo "ğŸ‰ Done!"
        env:
          HOMEPAGE: "https://github.com/you54f/hello_ffi"
          GH_TOKEN: ${{ github.token }}
